Create a Service for providing video/category data #10
OwnTube-tv/web-client pull request #19
Opened 2024-02-19 14:17 UTC by OGTor

# New Feature Submissions:

This will add Services for providing video/category data

Data can be is reusable for different components. 

### To Test
Open project and use 
npm run web
open the console in your desired web-browser
you will se different console logs with Category Labels, Videos, etc

2024-02-22 07:59 UTC, OGTor commented
## Updated upon reviews
#### Link to commited changes
https://ogtor.github.io/web-client/
## 
![image](https://github.com/OwnTube-tv/web-client/assets/112472401/129c18b2-514c-43b8-bb8f-dfae601fbaae)

2024-02-26 09:27 UTC, tryklick approved these changes

2024-02-28 08:14 UTC, ar9708 commented
FYI, checkboxes to tick @OGTor & @tryklick :

<img width="667" alt="image" src="https://github.com/OwnTube-tv/web-client/assets/123388211/7bb3ecb2-dc0d-431d-8b9e-3b98190557d5">

2024-02-28 08:18 UTC, ar9708 requested changes
FYI, checkboxes to tick @OGTor & @tryklick :

<img width="667" alt="image" src="https://github.com/OwnTube-tv/web-client/assets/123388211/7bb3ecb2-dc0d-431d-8b9e-3b98190557d5">

TODOs:
- [x] Linear history
- [x] Signed commints

2024-03-06 11:43 UTC, OGTor reviewed
Final fix for testData.json. 
This update should fix the problem with Actions not loading testData.json

2024-03-06 11:46 UTC, OGTor commented
> Final fix for testData.json. This update should fix the problem with Actions not loading testData.json

https://ogtor.github.io/web-client/

![image](https://github.com/OwnTube-tv/web-client/assets/112472401/2218b9fe-951d-4ba7-b207-54ac2eaadd60)

2024-04-01 21:00 UTC, OGTor reviewed
in videoServices.test.tsx it seems as this code part (line 47 - 50)
```
    type Category = {
      id: number;
      label: string;
    };
    
```
is not used in the testing

2024-04-16 15:24 UTC, tryklick approved these changes

2024-04-18 06:30 UTC, ar9708 reviewed
Good job! Starting to look neat and crispy. 🌟 Please see my comments below.

2024-04-18 06:30 UTC, ar9708 commented on OwnTube.tv/components/videosOverview.tsx
> +                  <Image source={{ uri: video.thumbnailUrl }} />
It looks right'ish, but when looking at the page here then there are no thumbnails rendered: https://ogtor.github.io/web-client/

Do you know why?

2024-04-18 06:30 UTC, ar9708 commented on OwnTube.tv/types.ts
> +}
I'm a bit unsure about specifying things as `readonly` here.. Let's talk about it during stand-up today.

2024-04-18 06:40 UTC, ar9708 commented on OwnTube.tv/types.ts
> +}
Not a shared type, move it to `components/videosOverview` please!

2024-04-19 08:19 UTC, ar9708 requested changes
@OGTor Your GitHub Actions pipeline is failing, please address!

2024-04-19 11:23 UTC, ar9708 approved these changes
Great, looking good! 🙃

2024-04-21 12:58 UTC, merged